using System.Runtime.ExceptionServices;

namespace _15Loops
{
    internal class Program
    {
        static void Main(string[] args)
        {
            for (int i = 0; i < 5; i++)
            {
                Console.WriteLine($"i");
            }

            for (int i = 1; i < 5; i++)
            {
                Console.WriteLine($"i");
            }

            for (int i = 0; i < 5; i++)
            {
                Console.WriteLine($"i");
            }

            for (int i = 0; i < 5; i++)
            {
                Console.WriteLine($"i");
            }

            for (int i = 0; i < 5; i++)
            {
                Console.WriteLine($"i");
            }

            for (int i = 0; i < 5; i++)
            {
                Console.WriteLine($"i");
            }

            for (int i = 0; i < 5; i++)
            {
                Console.WriteLine($"i");
            }

            for (int i = 0; i < 5; i++)
            {
                Console.WriteLine($"i");
            }

            for (int i = 0; i < 5; i++)
            {
                Console.WriteLine($"i");
            }

            for (int i = 0; i < 5; i++)
            {
                Console.WriteLine($"i");
            }

            for (int i = 0; i < 5; i++)
            {
                Console.WriteLine($"i");
            }

            for (int i = 0; i < 5; i++)
            {
                Console.WriteLine($"i");
            }

            for (int i = 0; i < 5; i++)
            {
                Console.WriteLine($"i");
            }

            for(int i = 0; i < 5; i++)
            {
                Console.WriteLine($"i");
            }

            for(int i = 0; i < 5; i++)
            {
                Console.WriteLine($"i");
            }
        }               
    }
}
